


#include <Windows.h>
#include "resource.h"
#include <stdio.h>
#include <wchar.h>
#include <tchar.h>
#include <psapi.h>
#include <Windowsx.h>
#include <assert.h>
#include "functions.h"
//#define __DEBUG


#define IDC_BUTTON_DIRECTORY_EXPORT			IDC_BUTTON_DIRECTORY_1
#define IDC_BUTTON_DIRECTORY_IMPORT			IDC_BUTTON_DIRECTORY_2
#define IDC_BUTTON_DIRECTORY_RESOURCE		IDC_BUTTON_DIRECTORY_3
#define IDC_BUTTON_DIRECTORY_EXCEPTION		IDC_BUTTON_DIRECTORY_4
#define IDC_BUTTON_DIRECTORY_BASERELOC		IDC_BUTTON_DIRECTORY_5
#define IDC_BUTTON_DIRECTORY_DEBUG			IDC_BUTTON_DIRECTORY_6
#define IDC_BUTTON_DIRECTORY_TLS			IDC_BUTTON_DIRECTORY_7
#define IDC_BUTTON_DIRECTORY_LOAD_CONFIG	IDC_BUTTON_DIRECTORY_8
#define IDC_BUTTON_DIRECTORY_BOUND_IMPORT	IDC_BUTTON_DIRECTORY_9
